version: '3.7'

services:
  backend:
    build:
      context: "C:\\Users\\betbe\\Desktop\\Montpellier cours\\DevOps\\simple-api-student-main"
    container_name: "simple_api_student2"
    networks:
      - app-network
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mon_postgres3:5432/db
      - SPRING_DATASOURCE_USERNAME=usr
      - SPRING_DATASOURCE_PASSWORD=pwd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  database:
    build:
      context: "C:\\Users\\betbe\\Desktop\\Montpellier cours\\DevOps"
    container_name: "mon_postgres3"
    networks:
      - app-network
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd

  httpd:
    build:
      context: "C:\\Users\\betbe\\Desktop\\Montpellier cours\\DevOps\\http"
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
      - database

networks:
  app-network:
